# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6500dbb972d50b159616a206c8d94c40193b2a82921a9ce2d7f917407151481cf4e524f275d200fa12a2574b5df3ff14913ee546ac7d695695972272d4a644c3

test:
  secret_key_base: 73266b71c7b7409f8caa3b136733811523fbce4eab9ab5b2a7735ab931348a51c05fd0746896054046c7679ab3ba1aab5ce0c8a105c24f723f07a0bcf7a6d443

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
